# Generated by Django 3.1.3 on 2020-11-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20201104_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asdf',
            old_name='user',
            new_name='name',
        ),
    ]
