# Generated by Django 3.1.2 on 2020-11-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20201104_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='asdf',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
