# Generated by Django 3.1.2 on 2020-11-07 11:01

from django.db import migrations, models
import loginapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_asdf_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asdf',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=loginapp.models.asdf.generate_filename),
        ),
    ]
