# Generated by Django 3.1.2 on 2020-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20201107_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='asdf',
            name='nameid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
