# Generated by Django 3.1.2 on 2020-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_asdf_nameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asdf',
            name='nameid',
            field=models.TextField(null=True),
        ),
    ]
