# Generated by Django 3.1.2 on 2020-11-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20201107_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asdf',
            name='nameid',
        ),
    ]
