# Generated by Django 3.1.2 on 2020-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_remove_asdf_nameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='asdf',
            name='yourid',
            field=models.TextField(null=True),
        ),
    ]
