# Generated by Django 2.2.4 on 2020-11-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_asdf_yourid'),
    ]

    operations = [
        migrations.AddField(
            model_name='asdf',
            name='kakao',
            field=models.TextField(null=True),
        ),
    ]
